package org.example;

/**
 * Starter application class generated by Gradle.
 *
 * Will be replaced by actual application code.
 */
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(final String[] args) {
        System.out.println(new App().getGreeting());
    }
}
